[package]
name = "sc_client"
version = "0.1.0"
authors = ["Ales Tsurko <ales.tsurko@gmail.com>"]
edition = "2018"

[dependencies]
config = "^0.9"
env_logger = "^0.6.0"
log = "^0.4"
os_pipe = "0.8.1"
rosc = "~0.1"
serde = "^1.0.0"
serde_derive = "^1.0.0"
uid = "0.1.4"
failure = "0.1"
